version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo build

  deploy: &deploy-env
    docker:
      -image: circleci/python:latest

    working_directory: ~/jhenrycode-vision

    steps:
      - checkout
      - setup_remote_docker

      - run: echo "deploy"
      - run: bash ./scripts/install_terraform.sh
      - run: bash ./infrastructure/${tag}/apply.sh
      - run: echo "deployed successfully"

  deploy_stage:
    <<: *deploy-env
    environment:
      tag: stage

workflows:
  version: 2

  stage_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_stage:
          filters:
            branches:
              only: master
          requires:
            - build 
            